const PostsActionTypes = {
  FETCH_POSTS_START: 'FETCH_POST_START',
  FETCH_POSTS_SUCCESS: 'FETCH_POST_SUCCESS',
  FETCH_POSTS_FAILURE: 'FETCH_POST_FAILURE',
  ADD_POST_START: 'ADD_POST_START',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FAILURE: 'ADD_POST_FAILURE',
  DELETE_POST_START: 'DELETE_POST_START',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',
  EDIT_POST_START: 'EDIT_POST_START',
  EDIT_POST_SUCCESS: 'EDIT_POST_SUCCESS',
  EDIT_POST_FAILURE: 'EDIT_POST_FAILURE',
  CLEAR_POST_MESSAGES: 'CLEAR_POST_MESSAGES',
};

export default PostsActionTypes;
