const CommentsActionTypes = {
  FETCH_COMMENTS_START: 'FETCH_COMMENT_START',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENT_SUCCESS',
  FETCH_COMMENTS_FAILURE: 'FETCH_COMMENT_FAILURE',
  ADD_COMMENT_START: 'ADD_COMMENT_START',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
  DELETE_COMMENT_START: 'DELETE_COMMENT_START',
  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',
  EDIT_COMMENT_START: 'EDIT_COMMENT_START',
  EDIT_COMMENT_SUCCESS: 'EDIT_COMMENT_SUCCESS',
  EDIT_COMMENT_FAILURE: 'EDIT_COMMENT_FAILURE',

  CLEAR_COMMENT_MESSAGES: 'CLEAR_COMMENT_MESSAGES',
};

export default CommentsActionTypes;
